public class AccountViewDto {
    public String companyInfoId;
    public String Name;
    public String Address;
    public String Environment;
    public boolean isReseller;
    public String ContactName;
    public String ContactEmail;
    public String Telephone;
    public String Fax;
    public String Description;
    public String CreationTime; // UMC format
    public String LastModified; // Datetime format
    public String ClientCode;
    public String Comments;
    public String UsernamePrefix;
    public Decimal Balance;
    public Decimal BalanceTreshold;

}