public with sharing class dutchBusinessGetDossierResponse {


// might need to rethink addresses and some more fields
        public list<String> trade_names;
        public String dossier_number;
        public String establishment_number;
        public String main_establishment_number;
        public Boolean indication_main_establishment;
        public String rsin_number;
        public String chamber_number;
        public String legal_form_code;
        public String legal_form_text;
        public String indication_organisation_code;
        public String legal_name;
        public String trade_name_45;
        public String trade_name_full;
        public String telephone_number;
        public String mobile_number;
        public String domain_name;
        public String contact_title1;
        public String contact_title2;
        public String contact_initials;
        public String contact_prefix;
        public String contact_surname;
        public String contact_gender;
        public String primary_sbi_code;
        public String secondary_sbi_code1;
        public String secondary_sbi_code2;
        public String primary_sbi_code_text;
        public String secondary_sbi_code1_text;
        public String secondary_sbi_code2_text;
        public Integer personnel;
        public Integer class_personnel;
        public Integer personnel_fulltime;
        public Integer class_personnel_fulltime;
        public Integer personnel_ci;
        public Integer class_personnel_ci;
        public Boolean indication_import;
        public Boolean indication_export;
        public Boolean indication_economically_active;
        public Boolean indication_non_mailing;
        public Boolean indication_bankruptcy;
        public Boolean indication_dip;
        public Long authorized_share_capital;
        public String authorized_share_capital_currency;
        public Long paid_up_share_capital;
        public String paid_up_share_capital_currency;
        public Long issued_share_capital;
        public String issued_share_capital_currency;

        public String establishment_address_original_address;
        public String establishment_address_original_postcode;
        public String establishment_address_original_city;
        public String establishment_address_original_street;
        public Integer establishment_address_original_house_number;
        public String establishment_address_original_house_number_addition;
        public String establishment_address_original_country;
        public String establishment_address_official_address;
        public String establishment_address_official_postcode;
        public String establishment_address_official_city;
        public String establishment_address_official_treet;
        public Integer establishment_address_official_house_number;
        public String establishment_address_official_house_number_addition;
        public String establishment_address_official_country;
        public String establishment_address_formatted_address;
        public String eestablishment_address_postcode;
        public String establishment_address_city;
        public String establishment_address_street;
        public Integer establishment_address_house_number;
        public String establishment_address_house_number_addition;
        public String establishment_address_country;

        public String correspondence_address_original_address;
        public String correspondence_address_original_postcode;
        public String correspondence_address_original_city;
        public String correspondence_address_original_street;
        public Integer correspondence_address_original_house_number;
        public String correspondence_address_original_house_number_addition;
        public String correspondence_address_original_country;
        public String correspondence_address_official_address;
        public String correspondence_address_official_postcode;
        public String correspondence_address_official_city;
        public String correspondence_address_official_treet;
        public Integer correspondence_address_official_house_number;
        public String correspondence_address_official_house_number_addition;
        public String correspondence_address_official_country;
        public String correspondence_address_formatted_address;
        public String ecorrespondence_address_postcode;
        public String correspondence_address_city;
        public String correspondence_address_street;
        public Integer correspondence_address_house_number;
        public String correspondence_address_house_number_addition;
        public String correspondence_address_country;
        public String personnel_reference_date;
        public String personnel_ci_reference_date;
        public String founding_date;
        public String discontinuation_date;
        public String continuation_date;
        public String establishment_date;

// TODO: add 
// public wwwWebservicesNlSoap.DutchBusinessInsolvencyArray insolvencies;
//        public wwwWebservicesNlSoap.DutchBusinessAnnualFinancialStatementSummary annual_financial_statement_summary;
//        public wwwWebservicesNlSoap.DutchBusinessStructure structure;
//        public wwwWebservicesNlSoap.DutchBusinessSBICollection sbi_collection;


}
