/**
 * Created by jaapbranderhorst on 2019-06-29.
 */

public with sharing class HeaderAuthenticateType {
    public String reactid;
    private String[] reactid_type_info = new String[]{'reactid','http://www.webservices.nl/soap/','string','1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://www.webservices.nl/soap/','true','false'};
    private String[] field_order_type_info = new String[]{'reactid'};
}