/**
 * Created by jaapbranderhorst on 2019-06-29.
 */

public with sharing class StringArray {
    public String[] item;
    private String[] item_type_info = new String[]{'item','http://www.webservices.nl/soap/','string','0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://www.webservices.nl/soap/','true','false'};
    private String[] field_order_type_info = new String[]{'item'};
}