public with sharing class UserCreateInputDto {
    public Integer accountid;
    public String nickname;
    public String password;
    public list<Integer> usergroups;
    public String email;
    public String companyname;
    public String address;
    public String contactname;
    public String contactemail;
    public String telephone;
    public String fax;
    public String clientcode;
    public String comments;
}
