/**
 * Created by jaapbranderhorst on 05/05/2020.
 */

public enum UpdateType {
    Update_Type_Activity,
    Update_Type_Branch,
    Update_Type_Capital,
    Update_Type_Chamber_No,
    Update_Type_Contact,
    Update_Type_Contact_Person,
    Update_Type_Correspondence_Address,
    Update_Type_Establishment,
    Update_Type_Establishment_Address,
    Update_Type_Financial_Status,
    Update_Type_Import_Export,
    Update_Type_Legalform,
    Update_Type_Name,
    Update_Type_New,
    Update_Type_Personnel,
    Update_Type_Removed,
    Update_Type_RSIN,
    Update_Type_Status,
    Update_Type_Subscription_Dates,
    Update_Type_Subsidiaries,
    Update_Type_Tradenames
}