/**
 * Created by jaapbranderhorst on 05/05/2020.
 */

public enum UpdateType {
    Activity,
    Branch,
    Capital,
    ChamberNo,
    Contact,
    ContactPerson,
    CorrespondenceAddress,
    Establishment,
    EstablishmentAddress,
    FinancialStatus,
    ImportExport,
    Legalform,
    Name,
    New,
    Personnel,
    Removed,
    RSIN,
    Status,
    SubscriptionDates,
    Subsidiaries,
    Tradenames
}