version: 2.1

orbs:
  slack: circleci/slack@3.4.2

commands:
  log_into_devhub:
    steps:
      - run:
          name: login into devhub
          command: |
            mkdir keys
            echo $HUB_SERVER_KEY_HEX | xxd -r -ps >> keys/hub.key
            openssl rsa -in keys/hub.key -check -noout
            sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile keys/hub.key --username $HUB_SFDC_USER --setdefaultdevhubusername -a hub
  create_user:
    description: "creates a user and stores the credentials and login in a file. Assumes the user is logged in into a devhub"
    parameters:
      org_username:
        description: the username or alias of the org to create users for
        type: string
      alias:
        description: the alias to create
        type: string
      email:
        description: the email address of the newly created user
        type: string
      path_to_user_definition:
        description: the path to the user definition
        type: string
      output_file_name:
        description: the file name to store the credentials of the created user
        type: string
    steps:
      - run:
          name: create user
          command: |
            sfdx force:user:create -u << parameters.org_username >> -a << parameters.alias >> -f << parameters.path_to_user_definition >> generatepassword=true email=<< parameters.email >>
            sfdx force:org:display -u << parameters.alias >> --json | jq '{username: .result.username, password: .result.password, instanceUrl: .result.instanceUrl}' >> << parameters.output_file_name >>
      - store_artifacts:
          path: << parameters.output_file_name >>


parameters:
  packageid:
    description: "The package id (starts with 0Ho). Copy it from the sfdx-project.json."
    type: string
    default: "0Ho0J000000k9bSSAQ"
  package_version_tag:
    description: "the package version’s tag"
    type: string
    default: ""
  packaging_scratch_org_definition_file:
    description: "the scratch org definition file used to build the package version. Should define all the right org shape/dependencies/features needed for the package"
    type: string
    default: "config/package-scratch-def.json"
  beta_test_scratch_org_definition_file:
    description: "the enterprise edition scratch org definition file used to install the beta. Should define all the right org shape/dependencies/features needed for installing the package"
    type: string
    default: "config/beta-test-scratch-def.json"
  build_wait:
    description: "the time in minutes the version create command waits until to return"
    type: integer
    default: 60
  email_beta_test:
    description: "the email for the beta test user"
    type: string
    default: "johan.van.den.hoek@appsolutely.nl"


jobs:
  run_apex_tests:
    description: Checks out the metadata, creates a new scratch org with the packaging scratch org def, pushes all metadata and runs all apex tests
    docker:
      - image: appsolutely/sfdx_circleci_container:latest
    resource_class: small
    environment:
      SFDX_MDAPI_TEMP_DIR: /root/project/metadata
      SFDX_LOG_LEVEL: debug
    steps:
      - checkout
      - log_into_devhub
      - run:
          name: create scratch org
          command:
            sfdx force:org:create -s -f << pipeline.parameters.packaging_scratch_org_definition_file >> -a circle_build_$CIRCLE_BUILD_NUM -d 1 -w 10
      - run:
          name: push source to scratch org
          command:
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
      - run:
          name: run apex tests
          command: |
            mkdir -p tests/junit
            sfdx force:apex:test:run -d tests/junit -r junit -w 20
      - store_test_results:
          path: tests/junit
      - store_artifacts:
          path: tests/junit
      - run:
          name: delete scratch org
          command: |
            sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p
      - run:
          name: Compress Metadata Artifacts
          when: always
          command: |
            tar -cvf metadata.tar /root/project/metadata
      - run:
          name: Compress sfdx log
          when: always
          command: |
            tar -cvf sfdx_log.tar /root/.sfdx/sfdx.log
      - store_artifacts:
          path: metadata.tar
          destination: metadata
      - store_artifacts:
          path: sfdx_log.tar
          destination: sfdx-log
  
  create_and_install_beta:
    description: checks out the metadata, creates a beta package, creates a new scratch org with the beta test scratch org def and creates users with the right permission sets
    parameters:
      skipvalidation:
        description: "--skipvalidation if validation needs to be skipped when creating a new beta package. Otherwise empty (default)"
        default: ""
        type: string
    docker:
      - image: appsolutely/sfdx_circleci_container:latest
    resource_class: small
    environment:
      SFDX_MDAPI_TEMP_DIR: /root/project/metadata
      SFDX_LOG_LEVEL: debug
    steps:
      - checkout
      - log_into_devhub
      - run:
          name: create beta package version
          no_output_timeout: 1.5h
          command: |
            packageversionid=$(sfdx force:package:version:create --package << pipeline.parameters.packageid >> -x -f << pipeline.parameters.packaging_scratch_org_definition_file >> --wait << pipeline.parameters.build_wait >> --tag "commit: $CIRCLE_SHA1" << parameters.skipvalidation >> --json | jq .result.SubscriberPackageVersionId)
            packageversionid="${packageversionid%\"}"
            packageversionid="${packageversionid#\"}"
            echo 'export packageversionid="'$packageversionid'"' >> $BASH_ENV
            echo 'export beta_package_created=true' >> $BASH_ENV
      - run:
          name: get version number
          command: |
            versionnumber=$(sfdx force:package:version:report -p $packageversionid --json | jq .result.Version)
            versionnumber="${versionnumber%\"}"
            versionnumber="${versionnumber#\"}"
            echo $versionnumber
            echo 'export versionnumber="'$versionnumber'"' >> $BASH_ENV
      - run:
          name: create beta test scratch org
          command: |
            sfdx force:org:create -s -f << pipeline.parameters.beta_test_scratch_org_definition_file >> -a test_beta_$versionnumber -d 30 -w 10 --nonamespace
      - run:
          name: install
          command: |
            sfdx force:package:install --package $packageversionid --noprompt --publishwait 5 -w 30
      - create_user:
          org_username: test_beta_$versionnumber
          alias: test-admin
          email: << pipeline.parameters.email_beta_test >>
          path_to_user_definition: config/companyinfo-admin-user-def.json
          output_file_name: test-admin-credentials.txt
      - create_user:
          org_username: test_beta_$versionnumber
          alias: test-sales
          email: << pipeline.parameters.email_beta_test >>
          path_to_user_definition: config/companyinfo-sales-user-def.json
          output_file_name: test-sales-credentials.txt
      - run:
          name: delete scratch org
          when: on_fail
          command: |
            sfdx force:org:delete -u test_beta_$versionnumber
      - store_artifacts:
          path: metadata.tar
          destination: metadata
      - store_artifacts:
          path: sfdx_log.tar
          destination: sfdx-log
      - slack/notify:
          message: "new scratch org with beta package available. Download the credentials to get access"
  
  upgrade_to_managed:
    docker:
      - image: appsolutely/sfdx_circleci_container:latest
    resource_class: small
    steps:
      - checkout
      - log_into_devhub
      - run:
          name: get latest package version and upgrade to managed package
          command: |
            packageversionid=$(sfdx force:package:version:list --verbose --json | jq -r --arg TAG "commit: $CIRCLE_SHA1" '.result[] | select(.Tag==$TAG) | .SubscriberPackageVersionId')
            sfdx force:package:version:promote --package $packageversionid --noprompt
#      - run:
#          name: merge into master
#          command: |
#            git checkout master
#            git merge $CIRCLE_BRANCH
#            git push origin master
#            git tag -a v$PACKAGE_MAJOR_VERSION.$CIRCLE_BUILD_NUM -m "$PACKAGE_VERSION_NAME v$PACKAGE_MAJOR_VERSION.$CIRCLE_BUILD_NUM"
#            git push origin --tags

workflows:
  version: 2.1
  feature_branch_push:
    jobs:
      - run_apex_tests:
          context: org-global
          filters:
            branches:
              only: /feature\/.*/
  
  develop_branch_push:
    jobs:
      - run_apex_tests:
          context: org-global
          filters:
            branches:
              only: 
                - develop
      - create_and_install_beta:
          context: org-global
          requires:
            - run_apex_tests
  
  release_branch_push:
    jobs:
      - run_apex_tests:
          context: org-global
          filters:
            branches:
              only: /release\/.*/
      - create_and_install_beta:
          context: org-global
          requires:
            - run_apex_tests
      - approve_upgrade_to_managed:
          type: approval
          requires:
            - create_and_install_beta
      - upgrade_to_managed:
          context: org-global
          requires:
            - approve_upgrade_to_managed




