/**
 * Created by jaapbranderhorst on 05/05/2020.
 */

public with sharing class LicenseManagementServiceImpl implements ILicenseManagementService {

    public User[] getAssignedUsersForLicenseType(String licenseType) {
        return null;
    }

    public void unassignLicenseType(String licenseType, User[] users) {
    }

    public void assignLicenseType(String licenseType, User[] users) {
    }


}