/**
 * Created by jaapbranderhorst on 22/05/2020.
 */

/**
 * Enum to make it easier to check if a user has access to a certain custom permission
 */

public enum Feature {
    COMPANY_INFO_ONLINE,
    CREDITSAFE_GET_REPORT,
    D_B_GET_REPORT,
    DUTCH_ADDRESSES,
    DUTCH_BUSINESS_GET_DOSSIER,
    DUTCH_BUSINESS_POSITIONS,
    DUTCH_BUSINESS_SEARCH,
    DUTCH_CHAMBER_OF_COMMERCE_EXTRACT,
    DUTCH_LEAD_GENERATOR,
    DUTCH_LOOK_A_LIKE_SERVICE,
    DUTCH_NEWS,
    DUTCH_VAT,
    INTERNATIONAL_ADDRESSES,
    INTERNATIONAL_BUSINESS_SEARCH
}
