/**
 * Created by tejaswinidandi on 15/05/2020.
 */

public inherited sharing class DutchAddressService {

    /*
     * Returns Dutch_Address_Postcode_Range__c if given address is found
     *
     * @param address
     */
//    public static Dutch_Address_Postcode_Range__c dutchAddressRangePostcodeSearch(String address){
//        return newInstance().dutchAddressRangePostcodeSearch(address);
//    }
//
//    public static IDutchAddressService newInstance() {
//        return (IDutchAddressService)Application.Service.newInstance(IDutchAddressService.class);
//    }

}