public with sharing abstract class CompanyInfoWebServiceSOAP {
 /*   public String endpoint_x = 'https://ws1.webservices.nl:443/soap_doclit.php';
    public Map<String,String> inputHttpHeaders_x;
    public Map<String,String> outputHttpHeaders_x;
    public String clientCertName_x;
    public String clientCert_x;
    public String clientCertPasswd_x;
    public Integer timeout_x;
    public HeaderAuthenticateType HeaderAuthenticate;
    public HeaderLoginType HeaderLogin;
    private String HeaderAuthenticate_hns = 'HeaderAuthenticate=http://www.webservices.nl/soap/';
    private String HeaderLogin_hns = 'HeaderLogin=http://www.webservices.nl/soap/';
    private String[] ns_map_type_info = new String[]{'http://www.webservices.nl/soap/', 'wwwWebservicesNlSoapVPROK'};


*/


}
